new change

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -60,52 +60,68 @@ jobs:
             echo "export PR_NUMBER=$PR_NUMBER" >> $BASH_ENV
             cd $GITHUB_CLI_PATH
 
-      - run:
-          name: Fetch all branches
-          command: |
-            git fetch --all
+            echo "export GITHUB_TOKEN=$STALE_GITHUB_TOKEN" >> $BASH_ENV
+
       - run:
           name: Generate configs at HEAD
-          working_directory: validation
           command: |
+            HEAD_SHA=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
+              "https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pulls/$PR_NUMBER" | jq -r '.head.sha')
+
+            # Checkout the HEAD SHA
+            git fetch origin $HEAD_SHA
+            git checkout $HEAD_SHA
+
             go run <<parameters.command>>/main.go HEAD
       - run:
           name: Generate configs on base branch
           command: |
-            cd $GITHUB_CLI_PATH
-            RES=$( poetry run github-cli get-pr-base-sha \
-              --github-token "${STALE_GITHUB_TOKEN}" \
-              --repo "${REPO}" \
-              --pr-number "${PR_NUMBER}" )
-            #check if RES does not contain error, continue otherwise exit
-            if [[ $RES == *"error"* ]]; then
-              echo "Error: $RES"
-              exit 1
-            fi
-            echo "export BASE_REV=$RES" >> $BASH_ENV
-      - run:
-          name: Generate configs on base branch
-          working_directory: validation
-          command: |
-            echo "Base branch revision: $BASE_REV"
-            git checkout $BASE_REV
+            # Fetch PR details using GitHub API
+            BASE_BRANCH=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
+              "https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pulls/$PR_NUMBER" | jq -r '.base.ref')
+
+            # Fetch the base branch
+            git fetch origin $BASE_BRANCH
+
+            # Checkout the base branch
+            git checkout $BASE_BRANCH
+
             go run <<parameters.command>>/main.go base
       - run:
           name: Compute diff
           working_directory: validation
           command: |
-            ./scripts/diff-configs.sh <<parameters.directory>>/output-base <<parameters.directory>>/output-HEAD
+            # Allow the script to continue even if the diff-configs.sh script returns a non-zero exit code
+            set +e
+
+            # Run the script and capture its output and exit code
+            OUTPUT=$(./scripts/diff-configs.sh <<parameters.directory>>/output-base <<parameters.directory>>/output-HEAD)
+            EXIT_CODE=$?
+
+            # Check if the output contains "panic"
+            if echo "$OUTPUT" | grep -q "panic"; then
+              echo "Error: The script output contains 'panic'"
+              exit 1
+            else
+              # Assign 0 or 1 to DIFF based on whether there was a difference
+              DIFF=$((EXIT_CODE == 0 ? 0 : 1))
+              echo "DIFF=$DIFF"
+            fi
+
+            echo "export DIFF=$DIFF" >> $BASH_ENV
+
+            # Restore error handling
+            set -e
           when: always
       - run:
-          name: If command failed, create or update comment on PR
-          when: on_fail
+          name: Handle PR Comment Based on DIFF
           command: |
-            RUN_ID=${CIRCLE_WORKFLOW_ID}
-            RUN_URL="https://app.circleci.com/pipelines/workflows/$RUN_ID"
+            RUN_URL="https://app.circleci.com/pipelines/workflows/${CIRCLE_WORKFLOW_ID}/jobs/${CIRCLE_BUILD_NUM}"
+
             MESSAGE="<<parameters.message>>"
             COMMENT_BODY="$MESSAGE. You can see the detail [here]($RUN_URL)."
-
             cd $GITHUB_CLI_PATH
+
             COMMENT_ID=$( poetry run github-cli get-pr-comments \
               --github-token "${STALE_GITHUB_TOKEN}" \
               --repo "${REPO}" \
@@ -115,42 +131,30 @@ jobs:
 
             COMMENT_ID=$(echo "$COMMENT_ID" | tr -d ' \n' | cut -d',' -f1)
 
-            if [ -n "$COMMENT_ID" ]; then
-              poetry run github-cli post-pr-comment \
-                --github-token "${STALE_GITHUB_TOKEN}" \
-                --repo "${REPO}" \
-                --pr-number "${PR_NUMBER}" \
-                --comment-body "${COMMENT_BODY}" \
-                --comment-id $COMMENT_ID
+
+            if [ "$DIFF" -eq 1 ]; then
+              if [ -n "$COMMENT_ID" ]; then
+                poetry run github-cli post-pr-comment \
+                  --github-token "${STALE_GITHUB_TOKEN}" \
+                  --repo "${REPO}" \
+                  --pr-number "${PR_NUMBER}" \
+                  --comment-body "${COMMENT_BODY}" \
+                  --comment-id $COMMENT_ID
+              else
+                poetry run github-cli post-pr-comment \
+                  --github-token "${STALE_GITHUB_TOKEN}" \
+                  --repo "${REPO}" \
+                  --pr-number "${PR_NUMBER}" \
+                  --comment-body "${COMMENT_BODY}"
+              fi
             else
-              poetry run github-cli post-pr-comment \
-                --github-token "${STALE_GITHUB_TOKEN}" \
-                --repo "${REPO}" \
-                --pr-number "${PR_NUMBER}" \
-                --comment-body "${COMMENT_BODY}"
-            fi
-      - run:
-          name: If command passed, remove a comment on the PR if it exists
-          when: on_success
-          command: |
-            MESSAGE="<<parameters.message>>"
-
-            cd $GITHUB_CLI_PATH
-            COMMENT_ID=$( poetry run github-cli get-pr-comments \
-              --github-token "${STALE_GITHUB_TOKEN}" \
-              --repo "${REPO}" \
-              --pr-number "${PR_NUMBER}" \
-              --message-substring "${MESSAGE}" \
-              --user-type "User" )
-
-            COMMENT_ID=$(echo "$COMMENT_ID" | tr -d ' \n' | cut -d',' -f1)
-
-            if [ -n "$COMMENT_ID" ]; then
-              poetry run github-cli delete-pr-comment \
-                --github-token "${STALE_GITHUB_TOKEN}" \
-                --repo "${REPO}" \
-                --pr-number "${PR_NUMBER}" \
-                --comment-id $COMMENT_ID
+              if [ -n "$COMMENT_ID" ]; then
+                poetry run github-cli delete-pr-comment \
+                  --github-token "${STALE_GITHUB_TOKEN}" \
+                  --repo "${REPO}" \
+                  --pr-number "${PR_NUMBER}" \
+                  --comment-id $COMMENT_ID
+              fi
             fi
 
 workflows:
