CI: New job to run periodic chain validation and minor refactoring (#464)
* CI: New job to run periodic chain validation and minor refactoring

* Add a new job and slack notification target to run validation of
  all chains on a periodic basis.
* Move the step to validate modified chains into it's own job and
  add that job to the `pr-checks` list.
* Alter existing cron job to run this new job instead of golang-test,
  which runs all unit tests.

* Add new slack channel ID and resolve review comments

* added id for new slack channel
* resolved other review comments

* incorrect tag to force validation failure

* Don't notify slack when running validation on mods

modifications in commits are evaluated against main and is used
either in PR commit checks or when commits are pushed to main (zero diff).
No need to notify failures to slack in the former case.

---------

Co-authored-by: Vinod Damle <vinod@oplabs.co>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -8,15 +8,27 @@ orbs:
 
 commands:
   notify-failures-on-main:
-    description: "Notify Slack"
+    description: "Notify Slack for CI job failures"
     parameters:
       channel:
         type: string
-        default: C03N11M0BBN
+        default: C03N11M0BBN # to slack channel `notify-ci-failures`
     steps:
       - slack/notify:
           channel: << parameters.channel >>
           event: fail
+          template: basic_fail_1
+          branch_pattern: main
+  notify-failures-on-validate-all:
+    description: "Notify Slack on any chain validation failures"
+    parameters:
+      channel:
+        type: string
+        default: C07GQQZDW1G # to slack channel `notify-superchain-validation-failures`
+    steps:
+      - slack/notify:
+          channel: << parameters.channel >>
+          event: pass
           template: basic_fail_1
           branch_pattern: main
   install-just:
@@ -42,6 +54,25 @@ commands:
           name: "Install toolchain"
           command: |
             rustup install nightly-x86_64-unknown-linux-gnu
+  install-foundry:
+    description: "Installs foundry"
+    steps:
+      - run:
+          # need foundry to execute 'cast call' within add-chain script
+          name: Install foundry
+          command: |
+            echo "SHELL=$SHELL"
+            # Set up directory structure
+            mkdir -p $HOME/.foundry/bin
+            echo 'export PATH="$HOME/.foundry/bin:$PATH"' >> $BASH_ENV
+            source $BASH_ENV
+
+            # Download foundryup and make it executable
+            curl -sSL "https://raw.githubusercontent.com/foundry-rs/foundry/master/foundryup/foundryup" -o $HOME/.foundry/bin/foundryup
+            chmod +x $HOME/.foundry/bin/foundryup
+
+            $HOME/.foundry/bin/foundryup
+            forge --version
 
 jobs:
   golang-lint:
@@ -74,22 +105,7 @@ jobs:
     steps:
       - checkout
       - install-just
-      - run:
-          # need foundry to execute 'cast call' within add-chain script
-          name: Install foundry
-          command: |
-            echo "SHELL=$SHELL"
-            # Set up directory structure
-            mkdir -p $HOME/.foundry/bin
-            echo 'export PATH="$HOME/.foundry/bin:$PATH"' >> $BASH_ENV
-            source $BASH_ENV
-
-            # Download foundryup and make it executable
-            curl -sSL "https://raw.githubusercontent.com/foundry-rs/foundry/master/foundryup/foundryup" -o $HOME/.foundry/bin/foundryup
-            chmod +x $HOME/.foundry/bin/foundryup
-
-            $HOME/.foundry/bin/foundryup
-            forge --version
+      - install-foundry
       - run:
           name: run superchain module unit tests
           command: just test-superchain
@@ -99,10 +115,32 @@ jobs:
       - run:
           name: run add-chain module unit tests
           command: just test-add-chain
+      - notify-failures-on-main
+  golang-validate-modified:
+    shell: /bin/bash -eo pipefail
+    executor:
+      name: go/default  # is based on cimg/go
+      tag: '1.21'
+    steps:
+      - checkout
+      - install-just
+      - install-foundry
       - run:
           name: run validation checks
           command: just validate-modified-chains main # TODO ideally this is the base branch
-      - notify-failures-on-main
+  golang-validate-all:
+    shell: /bin/bash -eo pipefail
+    executor:
+      name: go/default  # is based on cimg/go
+      tag: '1.21'
+    steps:
+      - checkout
+      - install-just
+      - install-foundry
+      - run:
+          name: run validation checks on all chains
+          command: just validate ""
+      - notify-failures-on-validate-all
   publish-bot:
     environment:
       NODE_AUTH_TOKEN: $NPM_TOKEN  # Use NPM_TOKEN as the auth token
@@ -167,6 +205,9 @@ jobs:
 workflows:
   hourly:
     jobs:
+      - golang-validate-all:
+          context:
+            - slack
       - golang-test:
           context:
             - slack
@@ -182,6 +223,7 @@ workflows:
       - golang-lint
       - golang-modules-tidy
       - golang-test
+      - golang-validate-modified
       - check-codegen
       - cargo-tests
       - cargo-lint
