refactoring

diff --git a/.circleci/continue_interactive.yml b/.circleci/continue_interactive.yml
--- a/.circleci/continue_interactive.yml
+++ b/.circleci/continue_interactive.yml
@@ -57,14 +57,14 @@ jobs:
     machine:
       image: ubuntu-2004:current
     steps:
-      # - run:
-      #     name: Verify Chain Parameter
-      #     command: |
-      #       if [ "<< pipeline.parameters.chain>>" = "__required__" ]; then
-      #         echo "Error: The 'chain' parameter is required but was not provided, skipping upload"
-      #         exit 1
-      #       fi
-      #       echo "export CHAIN=<< pipeline.parameters.chain>>" >> $BASH_ENV
+      - run:
+          name: Verify Chain Parameter
+          command: |
+            if [ "<< pipeline.parameters.chain>>" = "__required__" ]; then
+              echo "Error: The 'chain' parameter is required but was not provided, skipping upload"
+              exit 1
+            fi
+            echo "export CHAIN=<< pipeline.parameters.chain>>" >> $BASH_ENV
       - checkout
       - gcp-cli/install
       - gcp-oidc-authenticate
@@ -102,9 +102,9 @@ jobs:
 
 workflows:
   upload-chain-artifacts:
-    # when:
-    #   not:
-    #     equal: ["__required__", << pipeline.parameters.chain>>]
+    when:
+      not:
+        equal: ["__required__", << pipeline.parameters.chain>>]
     jobs:
       - upload-chain-artifacts:
           context: circleci-superchain-registry
