refactoring

diff --git a/.circleci/continue_interactive.yml b/.circleci/continue_interactive.yml
--- a/.circleci/continue_interactive.yml
+++ b/.circleci/continue_interactive.yml
@@ -6,11 +6,6 @@ orbs:
   gcp-cli: circleci/gcp-cli@3.0.1
   python: circleci/python@1.1.0
 
-parameters:
-  chain:
-    type: string
-    default: "__required__"
-
 commands:
   gcp-oidc-authenticate:
     description: "Authenticate with GCP using a CircleCI OIDC token."
@@ -57,14 +52,14 @@ jobs:
     machine:
       image: ubuntu-2004:current
     steps:
-      - run:
-          name: Verify Chain Parameter
-          command: |
-            if [ "<< pipeline.parameters.chain>>" = "__required__" ]; then
-              echo "Error: The 'chain' parameter is required but was not provided, skipping upload"
-              exit 1
-            fi
-            echo "export CHAIN=<< pipeline.parameters.chain>>" >> $BASH_ENV
+      # - run:
+      #     name: Verify Chain Parameter
+      #     command: |
+      #       if [ "<< pipeline.parameters.chain>>" = "__required__" ]; then
+      #         echo "Error: The 'chain' parameter is required but was not provided, skipping upload"
+      #         exit 1
+      #       fi
+      #       echo "export CHAIN=<< pipeline.parameters.chain>>" >> $BASH_ENV
       - checkout
       - gcp-cli/install
       - gcp-oidc-authenticate
@@ -87,24 +82,24 @@ jobs:
           command: |
             FOLDER="chains"
             FOLDER="ci-test-chains"
+            echo $chain
+            echo $CHAIN
+            # gsutil cp ./generate-genesis/output-${COMMIT_HASH}/${CHAIN}.json \
+            #   gs://${GCS_BUCKET}/${FOLDER}/${CHAIN}/genesis.json
+            # gsutil cp ./generate-rollup-config/output-${COMMIT_HASH}/${CHAIN}.json \
+            #   gs://${GCS_BUCKET}/${FOLDER}/${CHAIN}/rollup.json
 
-
-            gsutil cp ./generate-genesis/output-${COMMIT_HASH}/${CHAIN}.json \
-              gs://${GCS_BUCKET}/${FOLDER}/${CHAIN}/genesis.json
-            gsutil cp ./generate-rollup-config/output-${COMMIT_HASH}/${CHAIN}.json \
-              gs://${GCS_BUCKET}/${FOLDER}/${CHAIN}/rollup.json
-
-            # Upload with commit hash for historical records
-            gsutil cp ./generate-genesis/output-${COMMIT_HASH}/${CHAIN}.json \
-              gs://${GCS_BUCKET}/${FOLDER}/${CHAIN}/${COMMIT_HASH}/genesis.json
-            gsutil cp ./generate-rollup-config/output-${COMMIT_HASH}/${CHAIN}.json \
-              gs://${GCS_BUCKET}/${FOLDER}/${CHAIN}/${COMMIT_HASH}/rollup.json
+            # # Upload with commit hash for historical records
+            # gsutil cp ./generate-genesis/output-${COMMIT_HASH}/${CHAIN}.json \
+            #   gs://${GCS_BUCKET}/${FOLDER}/${CHAIN}/${COMMIT_HASH}/genesis.json
+            # gsutil cp ./generate-rollup-config/output-${COMMIT_HASH}/${CHAIN}.json \
+            #   gs://${GCS_BUCKET}/${FOLDER}/${CHAIN}/${COMMIT_HASH}/rollup.json
 
 workflows:
   upload-chain-artifacts:
-    when:
-      not:
-        equal: ["__required__", << pipeline.parameters.chain>>]
+    # when:
+    #   not:
+    #     equal: ["__required__", << pipeline.parameters.chain>>]
     jobs:
       - upload-chain-artifacts:
           context: circleci-superchain-registry
