refactor(ci): consolidate compute-config-diff commands and improve reporting structure

diff --git a/.circleci/main_config.yml b/.circleci/main_config.yml
--- a/.circleci/main_config.yml
+++ b/.circleci/main_config.yml
@@ -162,51 +162,6 @@ commands:
           repo: << parameters.REPO >>
           pr-number: << parameters.PR_NUMBER >>
 
-  compute-config-diff:
-    parameters:
-      command:
-        description: "Command to run to generate config files"
-        type: string
-      directory:
-        description: "Directory where config files are stored"
-        type: string
-      working_directory:
-        type: string
-        default: "validation"
-    steps:
-      - checkout
-      - run:
-          name: Generate configs
-          working_directory: <<parameters.working_directory>>
-          command: |
-            BASE_BRANCH="main"
-
-            # We are already in the Head of the PR after checkout
-            go run <<parameters.command>>/main.go HEAD
-
-            # Fetch the base branch
-            git fetch origin $BASE_BRANCH
-
-            # Checkout the base branch
-            git checkout $BASE_BRANCH
-
-            go run <<parameters.command>>/main.go base
-
-      - run:
-          name: OUTPUT DIFF -- LOOK HERE
-          working_directory: <<parameters.working_directory>>
-          command: |
-            # Allow the script to continue even if the diff-configs.sh script returns a non-zero exit code
-            set +e
-
-            # Run the script and capture its output and exit code
-            ./scripts/diff-configs.sh <<parameters.directory>>/output-base <<parameters.directory>>/output-HEAD
-            DIFF=$?
-            echo "export DIFF=$DIFF" >> "$BASH_ENV"
-            echo "export RUN_URL=${CIRCLE_BUILD_URL}" >> "$BASH_ENV"
-            # Restore error handling
-            set -e
-
 jobs:
   golang-lint:
     executor:
@@ -381,7 +336,7 @@ jobs:
       - checkout
       - run: echo "All golang-validate-genesis-allocs jobs suceeded"
 
-  compute-config-diff-and-report:
+  compute-config-diff:
     machine:
       image: ubuntu-2004:current
     parameters:
@@ -391,48 +346,93 @@ jobs:
       directory:
         description: "Directory where config files are stored"
         type: string
-      message:
-        description: "PR comment body prefixed message"
+      save_to:
+        description: "Variable to save the diff result"
         type: string
     steps:
       - checkout
-      - compute-config-diff:
-          working_directory: validation
-          command: <<parameters.command>>
-          directory: <<parameters.directory>>
       - run:
-          name: get pr number
+          name: Generate configs
+          working_directory: validation
           command: |
+            BASE_BRANCH="main"
+
+            # We are already in the Head of the PR after checkout
+            go run <<parameters.command>>/main.go HEAD
+
+            # Fetch the base branch
+            git fetch origin $BASE_BRANCH
+
+            # Checkout the base branch
+            git checkout $BASE_BRANCH
+
+            go run <<parameters.command>>/main.go base
+
+      - run:
+          name: Compute diff
+          working_directory: validation
+          command: |
+            # Allow the script to continue even if the diff-configs.sh script returns a non-zero exit code
+            set +e
+
+            # Run the script and capture its output and exit code
+            ./scripts/diff-configs.sh <<parameters.directory>>/output-base <<parameters.directory>>/output-HEAD
+            DIFF=$?
+            echo "export DIFF=$DIFF" >> <<parameters.save_to>>
+            echo "export RUN_URL=${CIRCLE_BUILD_URL}" >> <<parameters.save_to>>
+            # Restore error handling
+            set -e
+      - persist_to_workspace:
+          root: validation
+          paths:
+            - <<parameters.save_to>>
+
+  report-config-diff:
+    machine:
+      image: ubuntu-2004:current
+    parameters:
+      message:
+        description: "PR comment body prefixed message"
+        type: string
+      read_from:
+        description: "Variable to read the diff result"
+        type: string
+    steps:
+      - attach_workspace:
+          at: validation
+      - run:
+          name: Handle PR Comment Based on DIFF only if it is a PR
+          working_directory: validation
+          command: |
+            source <<parameters.read_from>>
+
             PR_NUMBER=$(echo "$CIRCLE_PULL_REQUEST" | sed 's|.*/||')
             REPO=${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
             echo "export PR_NUMBER=$PR_NUMBER" >> "$BASH_ENV"
             echo "export REPO=$REPO" >> "$BASH_ENV"
+            echo "export DIFF=$DIFF" >> "$BASH_ENV"
+
             echo $DIFF
             echo $RUN_URL
-      - when:
-          condition:
-            and: #only if it's a PR and there is a diff
-              - not: << pipeline.parameters.is_forked_pull_request >>
-              - << pipeline.parameters.is_pull_request >>
-          steps:
-            - utils/get-github-access-token:
-                repo: $REPO
-            - utils/get-github-pr-comments:
-                repo: $REPO
-                pr-number: $PR_NUMBER
-                message: << parameters.message >>
-            - report-on-diff-true:
-                REPO: $REPO
-                PR_NUMBER: $PR_NUMBER
-                COMMENT_ID: $COMMENT_ID
-                DIFF: $DIFF
-                COMMENT_BODY: "<< parameters.message >>. You can see the detail [here]($RUN_URL)."
-            - report-on-diff-false:
-                REPO: $REPO
-                PR_NUMBER: $PR_NUMBER
-                COMMENT_ID: $COMMENT_ID
-                DIFF: $DIFF
-                COMMENT_BODY: "<< parameters.message >>. You can see the detail [here]($RUN_URL)."
+
+      - utils/get-github-access-token:
+          repo: $REPO
+      - utils/get-github-pr-comments:
+          repo: $REPO
+          pr-number: $PR_NUMBER
+          message: << parameters.message >>
+      - report-on-diff-true:
+          REPO: $REPO
+          PR_NUMBER: $PR_NUMBER
+          COMMENT_ID: $COMMENT_ID
+          DIFF: $DIFF
+          COMMENT_BODY: "<< parameters.message >>. You can see the detail [here]($RUN_URL)."
+      - report-on-diff-false:
+          REPO: $REPO
+          PR_NUMBER: $PR_NUMBER
+          COMMENT_ID: $COMMENT_ID
+          DIFF: $DIFF
+          COMMENT_BODY: "<< parameters.message >>. You can see the detail [here]($RUN_URL)."
 
 workflows:
   hourly:
@@ -472,20 +472,50 @@ workflows:
       - golang-validate-modified
       - check-codegen
 
-  compute-config-diff-and-report-workflow:
+  compute-config-diff-and-report:
     when:
-      not:
-        equal: [scheduled_pipeline, << pipeline.trigger_source >>]
+      and:
+        - not:
+            equal: [scheduled_pipeline, << pipeline.trigger_source >>]
+        - not: << pipeline.parameters.is_forked_pull_request >>
     jobs:
-      - compute-config-diff-and-report:
+      - compute-config-diff:
           name: compute-genesis-diff
           command: "generate-genesis"
+          save_to: "GENESIS"
           directory: "generate-genesis"
+      - report-config-diff:
+          name: report-genesis-diff
+          read_from: "GENESIS"
           message: "Detected nonzero diff in genesis. This PR modifies the genesis data of at least one chain in the registry, which may or may not have been intended"
           context: circleci-repo-superchain-registry
-      - compute-config-diff-and-report:
+          requires: [compute-genesis-diff]
+      - compute-config-diff:
           name: compute-rollup-config-diff
           command: "generate-rollup-config"
+          save_to: "ROLLUP"
           directory: "generate-rollup-config"
+      - report-config-diff:
+          name: report-rollup-config-diff
+          read_from: "ROLLUP"
           message: "Detected nonzero diff in rollup config. This PR modifies the configuration of at least one chain in the registry, which may or may not have been intended"
           context: circleci-repo-superchain-registry
+          requires: [compute-rollup-config-diff]
+
+  compute-config-diff-only:
+    when:
+      and:
+        - not:
+            equal: [scheduled_pipeline, << pipeline.trigger_source >>]
+        - << pipeline.parameters.is_forked_pull_request >>
+    jobs:
+      - compute-config-diff:
+          name: compute-genesis-diff
+          command: "generate-genesis"
+          save_to: "GENESIS"
+          directory: "generate-genesis"
+      - compute-config-diff:
+          name: compute-rollup-config-diff
+          command: "generate-rollup-config"
+          save_to: "ROLLUP"
+          directory: "generate-rollup-config"
