superchain github actions - circleci migration (#700)
* diff migration

* combining workflows

* fix issues

* fix issues

* fix issues

* fix issues

* fix issues

* fix issues

* fix issues

* fix issues

* fix issues

* fix issues

* fix issues

* fix issues

* fix issues

* fix issues

* fix issues

* fix issues

* fix issues

* fix issues

* fix issues

* fix issues

* testing only value

* put  things back

* new change

* fix issues

* test only modification

* fix issue

* fix issue

* fix issue

* testing change

* reverting changes

* fix context

* testing actions

* test actions

* test actions

* test actions

* test actions

* test actions

* test actions

* test actions

* test actions

* test actions

* test actions

* test actions

* test actions

* test actions

* test actions

* fix build

* fix build

* fix build

* revert mode

* testing different images

* testing different images

* testing different images

* testing different images

* testing different images

* adding into continuation

* adding into continuation

* testingf differences

* testing athentication

* testing upload

* testing upload

* testing upload

* testing upload

* testing upload

* testing upload

* testing upload

* testing upload

* testing upload

* testing upload

* reverting chain

* testing upload

* testing upload

* testing upload

* testing upload

* refactoring

* refactoring

* refactoring

* refactoring

* refactoring

* refactoring

* refactoring

* refactoring

* refactoring

* refactoring

* refactoring

* testing metal

* testing metal

* refactoring

* refactoring

* refactoring

* refactoring

* refactoring

* refactoring

* refactoring

* refactoring

* refactoring

* refactoring

* test metal

* testing genesis validation job

* refactoring

* refactoring

* fix back files

* remove bin

* refactoring

* remove github actions

* complete changes

diff --git a/.circleci/main_config.yml b/.circleci/main_config.yml
--- a/.circleci/main_config.yml
+++ b/.circleci/main_config.yml
@@ -1,12 +1,13 @@
 version: 2.1
 orbs:
-  go: circleci/go@1.8.0
+  go: circleci/go@2.1.0
   node: circleci/node@5.2.0
   slack: circleci/slack@4.10.1
 parameters:
   go_version:
     type: string
     default: 1.22.7 # update CI Go version here
+
 commands:
   notify-failures-on-main:
     description: "Notify Slack for CI job failures"
@@ -245,13 +246,119 @@ jobs:
     steps:
       - checkout
       - run: echo "All golang-validate-genesis-allocs jobs suceeded"
+
+  compute-config-diff-and-report-with-pr-comment:
+    machine:
+      image: ubuntu-2004:current
+    parameters:
+      command:
+        description: "Command to run to generate config files"
+        type: string
+      directory:
+        description: "Directory where config files are stored"
+        type: string
+      message:
+        description: "PR comment body prefixed message"
+        type: string
+    steps:
+      - checkout
+      - run:
+          name: Get circleci tools and set initial environment variables
+          command: |
+            PR_NUMBER=$(echo "$CIRCLE_PULL_REQUEST" | sed 's|.*/||')
+            echo "export PR_NUMBER=$PR_NUMBER" >> $BASH_ENV
+      - run:
+          name: Generate configs
+          working_directory: validation
+          command: |
+            HEAD_SHA=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
+              "https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pulls/$PR_NUMBER" | jq -r '.head.sha')
+
+            # Checkout the HEAD SHA
+            git fetch origin $HEAD_SHA
+            git checkout $HEAD_SHA
+            go run <<parameters.command>>/main.go HEAD
+
+
+            # Fetch PR details using GitHub API
+            BASE_BRANCH=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
+              "https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pulls/$PR_NUMBER" | jq -r '.base.ref')
+
+            # Fetch the base branch
+            git fetch origin $BASE_BRANCH
+
+            # Checkout the base branch
+            git checkout $BASE_BRANCH
+
+            go run <<parameters.command>>/main.go base
+      - run:
+          name: Compute diff
+          working_directory: validation
+          command: |
+            # Allow the script to continue even if the diff-configs.sh script returns a non-zero exit code
+            set +e
+
+            # Run the script and capture its output and exit code
+            ./scripts/diff-configs.sh <<parameters.directory>>/output-base <<parameters.directory>>/output-HEAD
+            DIFF=$?
+            echo "export DIFF=$DIFF" >> $BASH_ENV
+
+            # Restore error handling
+            set -e
+          when: always
+      - run:
+          name: Handle PR Comment Based on DIFF
+          command: |
+            git clone --branch main --depth 1 https://github.com/ethereum-optimism/circleci-utils.git /tmp/circleci-utils
+            GITHUB_CLI_PATH="/tmp/circleci-utils/github_utility/github_cli"
+            pip install -r $GITHUB_CLI_PATH/requirements.txt
+            MAIN_PATH=$GITHUB_CLI_PATH/main.py
+            echo "export MAIN_PATH=$MAIN_PATH" >> $BASH_ENV
+
+            REPO="${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"
+
+            RUN_URL="${CIRCLE_BUILD_URL}"
+
+            MESSAGE="<<parameters.message>>"
+            COMMENT_BODY="$MESSAGE. You can see the detail [here]($RUN_URL)."
+            echo $COMMAND
+            COMMENT_ID=$( python $MAIN_PATH get-pr-comments \
+              --github-token "${GITHUB_TOKEN}" \
+              --repo "${REPO}" \
+              --pr-number "${PR_NUMBER}" \
+              --message-substring "${MESSAGE}" \
+              --user-type "User" )
+
+            COMMENT_ID=$(echo "$COMMENT_ID" | tr -d ' \n' | cut -d',' -f1)
+            COMMENT_OPTION=""
+            if [ -n "$COMMENT_ID" ]; then
+              COMMENT_OPTION="--comment-id $COMMENT_ID"
+            fi
+
+            if [ "$DIFF" -eq 1 ]; then
+                python $MAIN_PATH post-pr-comment \
+                  --github-token "${GITHUB_TOKEN}" \
+                  --repo "${REPO}" \
+                  --pr-number "${PR_NUMBER}" \
+                  --comment-body "${COMMENT_BODY}" \
+                  $COMMENT_OPTION
+            else
+              if [ -n "$COMMENT_ID" ]; then
+                python $MAIN_PATH delete-pr-comment \
+                  --github-token "${GITHUB_TOKEN}" \
+                  --repo "${REPO}" \
+                  --pr-number "${PR_NUMBER}" \
+                  --comment-id $COMMENT_ID
+              fi
+            fi
+
 workflows:
   hourly:
     # run workflow only when the hourly_build pipeline is triggered
     when:
       and:
-        - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
-        - equal: [ hourly_build, << pipeline.schedule.name >> ]
+        - equal: [scheduled_pipeline, << pipeline.trigger_source >>]
+        - equal: [hourly_build, << pipeline.schedule.name >>]
     jobs:
       - golang-validate-all:
           context:
@@ -263,8 +370,8 @@ workflows:
     # run workflow only when the nightly_build pipeline is triggered
     when:
       and:
-        - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
-        - equal: [ nightly_build, << pipeline.schedule.name >> ]
+        - equal: [scheduled_pipeline, << pipeline.trigger_source >>]
+        - equal: [nightly_build, << pipeline.schedule.name >>]
     jobs:
       - golang-promotion-test:
           context:
@@ -282,3 +389,18 @@ workflows:
       - golang-test
       - golang-validate-modified
       - check-codegen
+
+  compute-config-diff-and-report:
+    jobs:
+      - compute-config-diff-and-report-with-pr-comment:
+          name: compute-genesis-diff
+          command: "generate-genesis"
+          directory: "generate-genesis"
+          message: "Detected nonzero diff in genesis. This PR modifies the genesis data of at least one chain in the registry, which may or may not have been intended"
+          context: circleci-superchain-registry
+      - compute-config-diff-and-report-with-pr-comment:
+          name: compute-rollup-config-diff
+          command: "generate-rollup-config"
+          directory: "generate-rollup-config"
+          message: "Detected nonzero diff in rollup config. This PR modifies the configuration of at least one chain in the registry, which may or may not have been intended"
+          context: circleci-superchain-registry
